sudo: false
dist: xenial

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libboost-dev
        - libbz2-dev
        - libpcap-dev
        - libpcre2-dev
        - pkg-config
        - ragel
        - tree
    homebrew:
        packages:
        - boost
        - ccache
        - cmake
        - libpcap
        - pcre
        - ragel
        - tree
        update: true

language: go

go:
    - 1.9.x
    - 1.10.x
    - 1.11.x
    - 1.12.x
    - master

install:
    - go get -v github.com/hashicorp/go-multierror
    - go get -v github.com/google/gopacket
    - go get -v github.com/smartystreets/goconvey/convey

before_script:
    - .travis/build-hyperscan.sh

script:
    - go test ./...

env:
    global:
        - HYPERSCAN_ROOT=$HOME/hyperscan-$HYPERSCAN_VERSION
        - PKG_CONFIG_PATH=$HYPERSCAN_ROOT/lib/pkgconfig
        - DYLD_LIBRARY_PATH=$HYPERSCAN_ROOT/lib

matrix:
    include:
    - env: HYPERSCAN_VERSION=4.7.0  TAGS=hyperscan_v4
    - env: HYPERSCAN_VERSION=5.1.1  TAGS=hyperscan_v5

after_failure:
    - echo `pwd`
    - tree -h

cache:
    ccache: true
    directories:
    - $HYPERSCAN_ROOT
