sudo: false
dist: xenial

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libboost-dev
        - libbz2-dev
        - libpcap-dev
        - libpcre2-dev
        - libstdc++6
        - pkg-config
        - ragel
        - tree
    homebrew:
        packages:
        - boost
        - ccache
        - cmake
        - libpcap
        - pcre
        - ragel
        - tree
        update: true

language: go

go:
    - 1.9.x
    - 1.10.x
    - 1.11.x
    - 1.12.x
    - master

install:
    - go get -v github.com/hashicorp/go-multierror
    - go get -v github.com/google/gopacket
    - go get -v github.com/smartystreets/goconvey/convey

before_script:
    - .travis/build-hyperscan.sh

script:
    - go test -tags $TAGS ./... -v

env:
    matrix:
        - HYPERSCAN_VERSION=4.7.0  TAGS=hyperscan_v4
        - HYPERSCAN_VERSION=5.1.1  TAGS=hyperscan_v5

after_failure:
    - echo `pwd`
    - pkg-config --debug libhs
    - tree -h

cache:
    ccache: true
