[[constraint]]
  name = "github.com/google/gopacket"
  version = "1.1.14"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-multierror"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "1.6.3"

[prune]
  go-tests = true
  unused-packages = true
